package com.example.socialmedia.Mappers;

import org.mapstruct.Mapper;
import org.mapstruct.Mapping;

import com.example.socialmedia.DTOs.CreatePostRequest;
import com.example.socialmedia.DTOs.PostResponse;
import com.example.socialmedia.Entities.Post;

@Mapper(componentModel = "spring")
public interface PostMapper {

    @Mapping(source = "user.username", target = "username")
    PostResponse toPostResponse(Post post);

    @Mapping(target = "id", ignore = true) // Prevent mapping of autogenerated ID
    @Mapping(target = "user", ignore = true) // Skip setting user explicitly
    Post toPost(CreatePostRequest request);
}